#!/bin/sh

perpage=330     # Average words per page (including yaml blocks)

if test "$1" = "-h" || test "$1" = "--help"; then
cat <<EOF
Usage: jotter-stats [-h|--help] [--root DIR]

EOF
exit 0
fi
get_links() {
    cat .jotter/config | grep '^[ \t]*link[ \t]*' |
        sed 's,^[ \t]*link[ \t]*,,'
}
get_files() {
    get_links | while read link; do fd -ILe md . "$link"; done
    fd -ILe md
}

if test "$1" = "--root"; then
    cd "$2"; shift 2
else
    while true; do
        if test -d .jotter; then
            break
        elif test "$(pwd)" = "/"; then
            echo "No jotter root found" >&2
            exit 1
        else
            cd ..
        fi
    done
fi

words="$(get_files|xargs cat|wc -w)"
lines="$(get_files|xargs cat|wc -l)"

cat <<EOF
Root:         $(pwd)
Notes:        $(jotter-get --root . notes|wc -l)
References:   $(jotter-bib --stdout --root .|grep '^[ \t]*@'|wc -l)
Files:        $(get_files|wc -l)
Words:        $words
Lines:        $lines
Pages:        $((words/perpage))
EOF
