#!/bin/sh

while test "$1"; do
    if test "$1" = "-h" || test "$1" = "--help"; then
    cat <<EOF
Usage: jotter-keyword [OPTIONS] [KEYWORD]

Show all files associated with a specific keyword

Options:
    -c  --count     Show keyword counts (implies --list)
    -l  --list      List all keywords used in this jotter
EOF
    exit 0
    elif test "$1" = "-c" || test "$1" = "--count"; then
        uniq_opts="-c"
        list=1
    elif test "$1" = "-l" || test "$1" = "--list"; then
        list=1
    else
        list=0      # Keyword overrides list
        if test "$keyword"; then
            keyword="$keyword \+$1"
        else
            keyword="$1"
        fi
    fi
    shift
done

while true; do
    if test -d .jotter; then
        break
    elif test "$(pwd)" = "/"; then
        echo "No jotter root found. Run jotter-init to create a new jotter." >&2
        exit 1
    else
        cd ..
    fi
done

tmp="$(mktemp)"
printf '$for(keywords)$$keywords$' > "$tmp"
test "$keyword" && printf ': $filename$' >> "$tmp"
printf '$sep$\n$endfor$\n' >> "$tmp"

fd -e md | while read filename; do
    pandoc -t plain --template "$tmp" \
           -M filename="$filename" "$filename"
done | if test "$list" = 1; then
    sort | uniq $uniq_opts
elif test "$keyword" = ""; then
    echo "Please specify a keyword to search for" >&2
    exit 1
else
    grep "^$keyword: " | sed "s,$keyword: ,,g"
fi && exit=0 || exit=1

rm "$tmp"
exit "$exit"
