#!/bin/sh

perpage=330     # Average words per page (including yaml blocks)

if test "$1" = "-h" || test "$1" = "--help"; then
cat <<EOF
Usage: jotter-stats

Options:
    -h  --help      Print this help message and exit.

EOF
exit 0
fi

words="$(fd -e md|xargs cat|wc -w)"
lines="$(fd -e md|xargs cat|wc -l)"

cat <<EOF
Notes:        $(jotter-get notes|wc -l)
References:   $(jotter-bib|grep '^[ \t]*@'|wc -l)
Keywords:     $(jotter-keyword -l|wc -l)
Files:        $(fd -e md|wc -l)
Words:        $words
Lines:        $lines
Pages:        $((words/perpage))
EOF
