#!/bin/sh

if test "$1" = "-h" || test "$1" = "--help"; then
cat <<EOF
Usage: jotter-bib [-h|--help]

Extract all bibtex fields from markdown files.
EOF
exit 0
fi

cat <<EOF
% Composite Bibliography
% Jotter
% $(date -R)

EOF

fd -I -e md | while read filename; do
    cat "$filename" | awk '
        /^---$/ && yaml == 0        { yaml = 1; next }
        /^---$/ && yaml == 1        { yaml = 0; next }
        /^\.\.\.$/ && yaml == 1     { yaml = 0; next }
        /^bibtex:/ && yaml == 1     { bibtex = 1; next }
        /^[^ ]/ && bibtex == 1      { bibtex = 0; next }

        yaml && bibtex              { print }
        END                         { print "" }
    '
done | sed 's,^    ,,g'
