#!/usr/bin/env python3

import sys
from fnmatch import fnmatchcase
from jotter import *

_cli_help = """
Usage: jotter-rev [-h|--root DIR] <KEY|GLOB>...

Reverse lookup of citekeys. That is, find all notes that link to
a certain KEY. Specifying multiple KEYs is possible by providing
multiple arguments, by specifying a shell-like GLOB that matches
one or more keys, or by using a combination of both.

""".lstrip()

if __name__ == "__main__":
    if '-h' in sys.argv[1:] or '--help' in sys.argv[1:]:
        print(_cli_help)
        exit(0)
    cd_to_root()
    qs = sys.argv[1:]
    if not qs:
        print('At least one KEY or GLOB needs to be specified',
              file=sys.stderr)
        exit(1)
    for f in fd():
        for p in pages(f):
            m = False
            for q in qs:
                for k in cites(p):
                    if fnmatchcase(k, q): m = True; break
            if m and ids(p):
                print('-', ', '.join(sorted((f'@{k}' for k in ids(p)))))
