#!/bin/sh

if test "$1" = "-h" || test "$1" = "--help"; then
cat <<EOF
Usage: jotter-tags [-h|--help]

Write a ctags-like tags file with file references to bibliography
declarations.

EOF
exit 0
fi

fd -I -e md | while read filename; do
    cat "$filename" | awk -vfilename="$filename" '
        /^---$/ && yaml == 0        { yaml = 1; next }
        /^---$/ && yaml == 1        { yaml = 0; next }
        /^\.\.\.$/ && yaml == 1     { yaml = 0; next }
        /^bibtex:/ && yaml == 1     { bibtex = 1; next }
        /^[^ ]/ && bibtex == 1      { bibtex = 0; next }

        yaml && bibtex && $1 ~ /^@[^{]*{/ {
            tag = $1
            sub("^@[^{]*{", "", tag)
            sub(",$", "", tag)
            print tag"\t"filename"\t/"$1
        }
    '
done | sort > tags
