#!/bin/sh

print_help() {
cat <<EOF
Usage: jotter-bib [-h|--help] [--root DIR] [--stdout]

Extract all bibtex fields from markdown files. If a jotter
root directory is used (i. e. the '--root' flag is omitted),
the references are stored in a file named 'references.bib' in
the jotter root directory by default. Use '--stdout' to print
them to standard output instead.

EOF
}
to_outfile() {
    if test "$use_stdout" = 0; then cat >references.bib; else cat; fi
}
get_links() {
    cat .jotter/config | grep '^[ \t]*link[ \t]*' |
        sed 's,^[ \t]*link[ \t]*,,'
}
get_files() {
    get_links | while read link; do fd -ILe md . "$link"; done
    fd -ILe md
}

use_stdout=0
jotter_root=''
while test "$#" -gt 0; do
    case "$1" in
        -h|--help)  print_help; exit 0;;
        --root)     use_stdout=1; jotter_root="$2"; shift 2;;
        --stdout)   use_stdout=1; shift;;
    esac
done
if test "$jotter_root"; then
    cd "$jotter_root"
else
    while true; do
        if test -d .jotter; then
            break
        elif test "$(pwd)" = "/"; then
            echo "No jotter root found" >&2
            exit 1
        else
            cd ..
        fi
    done
fi

cat <<EOF | to_outfile
% Composite Bibliography
% Jotter
% $(date -R)

EOF

get_files |
    xargs cat |
    awk '
        ablock == 0 && bblock == 0 && /^```/    { ablock = 1; next }
        ablock == 0 && bblock == 0 && /^~~~/    { bblock = 1; next }
        ablock == 1 && /^```/                   { ablock = 0 }
        bblock == 1 && /^~~~/                   { bblock = 0 }
        ablock == 1                             { next }
        bblock == 1                             { next }

        /^---$/ && yaml == 0        { mayyaml = 1; next }
        mayyaml == 1 && /[^ \t]/    { yaml = 1 }
        mayyaml == 1                { mayyaml = 0 }
        /^---$/ && yaml == 1        { yaml = 0; next }
        /^\.\.\.$/ && yaml == 1     { yaml = 0; next }
        /^bibtex:/ && yaml == 1     { bibtex = 1; next }
        /^[^ ]/ && bibtex == 1      { bibtex = 0; next }

        yaml && bibtex              { print }
    ' |
    sed 's,^    ,,g' | to_outfile
