#!/bin/sh

if test "$1" = "-h" || test "$1" = "--help"; then
cat <<EOF
Usage: jotter-init [PATH]

Initialize a new jotter in PATH (default: current
working directory)

EOF
exit 0
fi

origin="$(pwd)"
while true; do
    if test -d .jotter; then
        echo "There is already a jotter root in $(pwd)" >&2
        exit 1
    elif test "$(pwd)" = "/"; then
        break
    else
        cd ..
    fi
done
cd "$origin"

test "$#" -gt 1 && mkdir -p "$1" && cd "$1"
mkdir .jotter
echo "Initialized new jotter in $(pwd)"
