#!/usr/bin/env python3

import sys
from fnmatch import fnmatchcase
from jotter import *

_cli_help = """
Usage: jotter-ls [KEY|GLOB]...

Print a list of all keys in the jotter. These keys can be filtered by
specifying a number of KEYs that shall be included, by specifying one
or more GLOBs that match certain keys, or using a combination of both.

Options:
    -h  --help      Print this help message and exit
""".lstrip()

if __name__ == "__main__":
    if '-h' in sys.argv[1:] or '--help' in sys.argv[1:]:
        print(_cli_help)
        exit(0)
    qs = sys.argv[1:]
    keys = set()
    for f in fd():
        for p in pages(f):
            p_ids = ids(p)
            for k in p_ids:
                keys.add(k)
    def printkey(key):
        print(f'- @{key}')
    for k in sorted(keys):
        if not qs: printkey(k); continue
        for q in qs:
            if fnmatchcase(k, q): printkey(k); break
