#!/bin/sh

if test "$1" = "-h" || test "$1" = "--help"; then
cat <<EOF
Usage: jotter [-h|--help] COMMAND [--root DIR] [ARG]...

See 'jotter COMMAND --help' for further information about
individual commands.

Most commands (except for 'jotter init') accept a '--root' option
that causes the command to skip searching a jotter root directory
created with 'jotter init'.  This may be convenient to use the
commands on the subset of a given jotter or even outside of any
initialized jotter.

Commands
    init        Initialize a new jotter by marking a certain
                directory as the jotter's root dir
    ln          Link a different jotter into this one
    bib         Extract bibliographic information from files
    tags        Create a ctags-like 'tags' file with citekeys
                as identifiers
    stats       Display some statistical information about the
                files in this jotter
    ls          Print a list of citekeys found in this jotter
    rev         Perform a reverse lookup of citekeys (i. e. find
                all notes that link to a certain entry)
    get         Get certain pieces of information about the graph
                constituted by the linked notes

EOF
elif test "$(which jotter-$1 2>/dev/null)"; then
    jotter-$@
else
    echo "Command not found: jotter-$1" >&2
    exit 1
fi
